CREATE TABLE EVENTBOARD(
eve_seq NUMBER(10) NOT NULL,
eve_writer VARCHAR2(10) NOT NULL,
eve_title VARCHAR2(1000),
eve_content VARCHAR2(2000),
eve_regDate DATE DEFAULT SYSDATE,
eve_count NUMBER(10),
eve_img VARCHAR2(2000),
CONSTRAINT EVENTBOARD_PK_eve_seq PRIMARY KEY(eve_seq)
);

CREATE SEQUENCE EVENTSEQ;

INSERT INTO EVENTBOARD
VALUES(EVENTSEQ.NEXTVAL,'ADMIN','제목테스트','내용테스트',sysdate,0,'null');

	SELECT B.* 
		FROM (SELECT A.*, ROWNUM AS RNUM
		FROM (SELECT * FROM EVENTBOARD ORDER BY eve_regDate DESC) A) B
		WHERE RNUM BETWEEN 1 AND 10;
		
alter table eventboard
add(eve_addr VARCHAR2(2000)); 

	SELECT * FROM EVENTBOARD;